name: Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t yourdockerhubusername/yourimagename:latest .
        docker push yourdockerhubusername/yourimagename:latest

    - name: Deploy to Render
      run: |
        curl -X POST -H "Accept: application/json" \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{"serviceId": "your-service-id"}' \
        https://api.render.com/v1/services/your-service-id/deploys
